title: DeepWrite
description: 손제연의 논증적 글쓰기 공식 강의자료 공유 및 학습 지원 사이트
theme: just-the-docs

url: https://DeepWrite.github.io/
logo: "/assets/images/DeepWriteLogo.png"
favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Jeyoun's Personal Homepage: https://jeyounson.github.io/
